version: '3.8'

services:
  web:
    build: 
       context: .
       dockerfile: ./Dockerfile
    container_name: food_mania
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+mysqldb://root:root@db/food_mania_db
    command: >
      sh -c "./wait-for-it.sh db:3306 -- python3 main.py"

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food_mania_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
